- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

- docker tag udagram-api-feed hiimkol/udagram-api-feed:v1
- docker tag udagram-api-user hiimkol/udagram-api-user:v1
- docker tag udagram-frontend hiimkol/udagram-frontend:v1
- docker tag udagram-reverseproxy hiimkol/udagram-reverseproxy:v1

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push hiimkol/udagram-api-feed:v1
- docker push hiimkol/udagram-api-user:v1
- docker push hiimkol/udagram-frontend:v1
- docker push hiimkol/udagram-reverseproxy:v1
